### ISSUE TITLE
LinkedIn account doesn't show up

### ISSUE THREAD

**Issue by meganpiggy** [Gladior-B-V/linkedin-ads-connector#1]
Hi! I have full access to my company's LinkedIn account. However when I try to connect to this account in Data Hub it does not show up. How do I connect the company LinkedIn account so I can create reports on the ads we will be running? 

<img width="913" alt="Screenshot 2023-06-28 at 16 11 29" src="https://github.com/Gladior-B-V/linkedin-ads-connector/assets/129306699/60904a02-e173-4bb0-88fe-ed25a458023e">

Thank you! 

Kind regards, 

Megan

**Comment by zoedufrenne** [comment]
Hi @meganpiggy ,

Thanks for letting us know.
We do not see any errors popping up in the system that there is an issue. Is the credential you added to the Data Hub the account you are accessing with?
