### ISSUE TITLE
Member Company Name Not Displaying

### ISSUE THREAD

**Issue by bhabecker** [Gladior-B-V/linkedin-ads-connector#2]
Hi, 

I recently connected the gladiator LinkedIn ads connector to Looker studio to display demographic repots on my ads (i.e. member company names sorted by ad clicks). Unfortunately, the company name is only displaying urn:li:organization:1586 (or another number). 

Any idea of how to get this string to translate to the member company name in the chart (image attached)?

Thanks,

Ben
![Member Company by Clicks Chart](https://github.com/Gladior-B-V/linkedin-ads-connector/assets/167330426/c0aa72db-b75c-41ad-ac36-e7c0417176f2)
![Member company by clicks chart setup](https://github.com/Gladior-B-V/linkedin-ads-connector/assets/167330426/92e697a2-b78f-41d0-abe3-f10fefbfa7a5)

**Comment by rkooiker** [comment]
Hi @bhabecker, this is currently not supported by our connector. Maybe in the future.
